### ISSUE TITLE
Ignore HTTPS certificate errors

### ISSUE THREAD

**Issue by bkil** [shukon/maubot-fetchimage#1]
https://docs.aiohttp.org/en/stable/client_advanced.html#ssl-control-for-tcp-sockets

**Comment by shukon** [comment]
Mh :thinking: are there any security implications with this?
Do you have a link for testing this you could share here? I don't have a non-SSL site handy, having one to test it would speed this up ^^

**Comment by bkil** [comment]
For unfurling cat images, I view the potential security impact low at the moment. :cat2: 

Here's something for you to have some fun with:
* https://a.uguu.se/ppKZNMPO.png
* https://github.com/nokonoko/uguu

**Comment by shukon** [comment]
> For unfurling cat images, I view the potential security impact low at the moment.

Fair enough. Added a warning for good measure though...
